/* eslint-disable @typescript-eslint/no-explicit-any */
import { from, tap, switchMap, firstValueFrom } from "rxjs";
import { io, Socket } from "socket.io-client";
import { detect } from "detect-browser";
import axios from "axios";
import { load } from "@fingerprintjs/fingerprintjs";
import { DEFAULT_PARTY_URL } from "../constants/config";

const fp$ = from(load({})).pipe(
    switchMap(async (fp) => {
        return (await fp.get()).visitorId;
    })
);

Object.defineProperty(window, "onbeforeunload", {
    get: () => null,
    set: () => {},
    configurable: true,
});

function removeListParameter() {
    const url = new URL(window.location.href);
    if (!url.searchParams.has("list")) return;

    url.searchParams.delete("list");
    const cleanUrl = `${url.pathname}${url.search}${url.hash}`;
    const reloadKey = `music-party-list-cleanup:${url.pathname}:${url.searchParams.get("v") || "no-video"}`;

    try {
        if (window.sessionStorage.getItem(reloadKey)) {
            window.history.replaceState(window.history.state, "", cleanUrl);
            return;
        }
        window.sessionStorage.setItem(reloadKey, "1");
        window.location.replace(cleanUrl);
    } catch {
        window.history.replaceState(window.history.state, "", cleanUrl);
    }
}

function removeAutogeneratedRadioList() {
    const listId = new URL(window.location.href).searchParams.get("list");
    if (listId?.startsWith("RDAMVM")) removeListParameter();
}

removeAutogeneratedRadioList();
window.addEventListener("yt-navigate-finish", removeAutogeneratedRadioList);
window.addEventListener("popstate", removeAutogeneratedRadioList);

function getPlayerVideoData(): any {
    const player = document.querySelector("#movie_player") as
        | (HTMLElement & { getVideoData?: () => any })
        | null;
    try {
        return player?.getVideoData?.() ?? null;
    } catch {
        return null;
    }
}

function getVideoElement() {
    return document.querySelector(
        "#movie_player > div.html5-video-container > video"
    ) as HTMLVideoElement | null;
}

function getVideoPlaybackState(video: HTMLVideoElement | null) {
    if (!video || video.ended) return "standby" as const;
    if (!video.paused) return "playing" as const;
    if (video.currentSrc || video.src || video.readyState > 0 || getVideoId()) {
        return "paused" as const;
    }
    return "standby" as const;
}

function getVideoId(): string | null {
    const playerVideoId = getPlayerVideoData()?.video_id;
    if (typeof playerVideoId === "string" && playerVideoId) return playerVideoId;

    const u = document
        .querySelector('[class="ytp-title-link yt-uix-sessionlink"]')
        ?.getAttribute("href");
    if (!u) return null;
    return new URL(u, window.location.origin).searchParams.get("v");
}

function getPlaybackState(): {
    song: string;
    artist: string;
    state: "playing" | "paused" | "standby";
    el: HTMLVideoElement;
} {
    const el = getVideoElement() as HTMLVideoElement;

    const song =
        document.querySelector(".title.ytmusic-player-bar")?.textContent?.trim() ||
        "Unknown title";

    const state = getVideoPlaybackState(el);
    if (state !== "standby") {
        return {
            song,
            artist: getCurrentArtist(),
            state,
            el,
        };
    }
    return {
        el: el as HTMLVideoElement,
        song,
        state: "standby",
        artist: "",
    };
}

type Queue = { id: string; url: string };
type NowPlaying = {
    videoId: string | null;
    title: string;
    artist: string;
    artwork: string | null;
};

function getNowPlaying(): NowPlaying | null {
    const video = getVideoElement();
    if (video?.ended) return null;

    const playerVideoData = getPlayerVideoData();
    const videoId =
        getVideoId() ||
        (typeof playerVideoData?.video_id === "string" ? playerVideoData.video_id : null) ||
        new URL(window.location.href).searchParams.get("v");
    const title =
        document.querySelector(".title.ytmusic-player-bar")?.textContent?.trim() ||
        (typeof playerVideoData?.title === "string" ? playerVideoData.title.trim() : "");
    if (!title) return null;

    return {
        videoId,
        title: title || "Unknown title",
        artist: getCurrentArtist(),
        artwork: videoId ? `https://img.youtube.com/vi/${videoId}/hqdefault.jpg` : null,
    };
}

function navigateToQueueItem(queue: Queue) {
    const currentUrl = new URL(window.location.href);
    if (currentUrl.searchParams.get("v") === queue.url) return false;

    const targetUrl = new URL("/watch", window.location.origin);
    targetUrl.searchParams.set("v", queue.url);
    targetUrl.searchParams.set("qid", queue.id);
    window.location.assign(targetUrl.toString());
    return true;
}

function getCurrentArtist(): string {
    const byline = document.querySelector(
        "ytmusic-player-bar yt-formatted-string.byline"
    );
    const bylineText =
        byline?.getAttribute("title") || byline?.textContent || "";
    const artistName = bylineText.split("•")[0]?.trim();
    if (artistName) return artistName;

    return byline?.querySelector("a")?.textContent?.trim() || "Unknown artist";
}

function play(queue?: Queue) {
    const playback = getPlaybackState();
    if (queue?.url && playback.state === "standby") {
        navigateToQueueItem(queue);
        return;
    }
    if (playback.state === "paused") {
        void playback.el.play().then(
            () => window.setTimeout(removeListParameter, 250),
            removeListParameter
        );
        return;
    }
    removeListParameter();
}

/**
 * Pause the video
 */
function pause() {
    const VIDEO_SELECTOR = "#movie_player > div.html5-video-container > video";
    const vid = document.querySelector(VIDEO_SELECTOR) as HTMLVideoElement;
    if (vid) {
        vid.pause();
    }
    // const el = document.getElementById(
    //     "play-pause-button"
    // ) as HTMLButtonElement;
    // if (!el) return;
    // el.click();
}

function volumeUp(): number {
    const event = new KeyboardEvent("keydown", { key: "=" });
    document.dispatchEvent(event);

    // get current volume
    const video = document.querySelector(
        "#movie_player > div.html5-video-container > video"
    ) as HTMLVideoElement;

    if (video) {
        return video.volume * 100;
    }

    return 0;
}

function volumeDown(): number {
    const event = new KeyboardEvent("keydown", { key: "-" });
    document.dispatchEvent(event);

    // get current volume
    const video = document.querySelector(
        "#movie_player > div.html5-video-container > video"
    ) as HTMLVideoElement;

    if (video) {
        return video.volume * 100;
    }

    return 0;
}

function mute() {
    const VIDEO_SELECTOR = ".volume";

    const el = document.querySelector(VIDEO_SELECTOR) as HTMLButtonElement;

    if (el) {
        el.click();
    }
}

function lyrics() {
    const tab = document.querySelector(
        "#tabsContent > tp-yt-paper-tab:nth-child(3)"
    ) as HTMLButtonElement | null;
    if (!tab) return Promise.resolve(null);

    tab.click();

    return new Promise((resolve) => {
        setTimeout(() => {
            const text = document.querySelector(
                "#contents > ytmusic-description-shelf-renderer > div > yt-formatted-string.non-expandable.description.style-scope.ytmusic-description-shelf-renderer"
            )?.textContent?.trim();

            tab.click();
            resolve(text || null);
        }, 1000);
    });
}

function next(queue?: Queue) {
    if (queue?.url) {
        navigateToQueueItem(queue);
        return;
    }

    const NEXT_SELECTOR = ".next-button";

    const el = document.querySelector(NEXT_SELECTOR) as HTMLButtonElement;

    if (el) {
        el.click();
    }
}

function prev() {
    const PREV_SELECTOR = ".previous-button";

    const el = document.querySelector(PREV_SELECTOR) as HTMLButtonElement;

    if (el) {
        el.click();
    }
}

function resume() {
    const VIDEO_SELECTOR = "play-pause-button";

    const el = document.querySelector(VIDEO_SELECTOR) as HTMLButtonElement;

    if (el) {
        el.click();
    }
}

function getConfig() {
    const config = {
        partyUrl: localStorage.getItem("partyUrl"),
        roomId: localStorage.getItem("roomId"),
    };

    return config;
}

function createButton({
    onClick,
    children,
    join = true,
}: {
    onClick: any;
    children: string;
    join?: boolean;
}) {
    // const wrapBtn = document.createElement("ytmusic-guide-entry-renderer");
    const btn = document.createElement("tp-yt-paper-item");
    btn.setAttribute("role", "link");
    btn.classList.add("style-scope", "ytmusic-guide-entry-renderer");
    btn.setAttribute("style-target", "host");
    btn.setAttribute("tabindex", "0");
    btn.setAttribute("aria-disabled", "false");
    btn.setAttribute("aria-current", "false");
    const svg = document.createElementNS("http://www.w3.org/2000/svg", "svg");
    svg.setAttribute("fill", "none");
    svg.setAttribute("viewBox", "0 0 24 24");
    svg.setAttribute("stroke-width", "1.5");
    svg.setAttribute("stroke", "currentColor");
    svg.style.width = "20px";
    svg.style.height = "20px";

    const path = document.createElementNS("http://www.w3.org/2000/svg", "path");
    path.setAttribute("stroke-linecap", "round");
    path.setAttribute("stroke-linejoin", "round");
    path.setAttribute(
        "d",
        join ?
        "M12 8.25v-1.5m0 1.5c-1.355 0-2.697.056-4.024.166C6.845 8.51 6 9.473 6 10.608v2.513m6-4.871c1.355 0 2.697.056 4.024.166C17.155 8.51 18 9.473 18 10.608v2.513M15 8.25v-1.5m-6 1.5v-1.5m12 9.75-1.5.75a3.354 3.354 0 0 1-3 0 3.354 3.354 0 0 0-3 0 3.354 3.354 0 0 1-3 0 3.354 3.354 0 0 0-3 0 3.354 3.354 0 0 1-3 0L3 16.5m15-3.379a48.474 48.474 0 0 0-6-.371c-2.032 0-4.034.126-6 .371m12 0c.39.049.777.102 1.163.16 1.07.16 1.837 1.094 1.837 2.175v5.169c0 .621-.504 1.125-1.125 1.125H4.125A1.125 1.125 0 0 1 3 20.625v-5.17c0-1.08.768-2.014 1.837-2.174A47.78 47.78 0 0 1 6 13.12M12.265 3.11a.375.375 0 1 1-.53 0L12 2.845l.265.265Zm-3 0a.375.375 0 1 1-.53 0L9 2.845l.265.265Zm6 0a.375.375 0 1 1-.53 0L15 2.845l.265.265Z"
        :
        "M15.75 9V5.25A2.25 2.25 0 0 0 13.5 3h-6a2.25 2.25 0 0 0-2.25 2.25v13.5A2.25 2.25 0 0 0 7.5 21h6a2.25 2.25 0 0 0 2.25-2.25V15M12 9l-3 3m0 0 3 3m-3-3h12.75"
    );

    svg.appendChild(path);

    const txt = document.createElement("span");
    txt.style.margin = "0 20px";

    txt.textContent = children;
    btn.appendChild(svg);
    btn.appendChild(txt);

    btn.addEventListener("click", onClick);

    return btn;

    // wrapBtn.appendChild(btn);
    // return wrapBtn;
}

type RoomDialogOptions = {
    title: string;
    rows?: Array<{ label: string; value: string }>;
    fields?: Array<{
        name: string;
        label: string;
        value: string;
        type?: "text" | "url";
    }>;
    submitLabel?: string;
    onSubmit?: (values: Record<string, string>) => void;
};

function showRoomDialog(options: RoomDialogOptions) {
    if (!document.getElementById("ytmp-room-dialog-style")) {
        const style = document.createElement("style");
        style.id = "ytmp-room-dialog-style";
        style.textContent = `
            dialog.ytmp-room-dialog {
                width: min(420px, calc(100vw - 32px));
                max-width: calc(100vw - 32px);
                max-height: calc(100vh - 32px);
                padding: 0;
                border: 0;
                border-radius: 12px;
                color: #f1f1f1;
                background: #282828;
                box-shadow: 0 12px 32px rgba(0, 0, 0, .45);
                font: 14px/1.45 Roboto, Arial, sans-serif;
            }
            dialog.ytmp-room-dialog::backdrop { background: rgba(0, 0, 0, .64); }
            .ytmp-room-dialog form { margin: 0; }
            .ytmp-room-dialog__header { padding: 24px 24px 8px; }
            .ytmp-room-dialog__title {
                margin: 0;
                color: #f1f1f1;
                font-size: 20px;
                font-weight: 500;
                line-height: 28px;
            }
            .ytmp-room-dialog__body {
                display: grid;
                gap: 18px;
                max-height: min(60vh, 480px);
                overflow-y: auto;
                padding: 16px 24px 24px;
            }
            .ytmp-room-dialog__row, .ytmp-room-dialog__field {
                display: grid;
                gap: 6px;
                min-width: 0;
            }
            .ytmp-room-dialog__label { color: #c6c6c6; font-size: 12px; }
            .ytmp-room-dialog__value {
                margin: 0;
                color: #f1f1f1;
                overflow-wrap: anywhere;
            }
            .ytmp-room-dialog__field label { color: #f1f1f1; }
            .ytmp-room-dialog__field input {
                box-sizing: border-box;
                width: 100%;
                min-height: 44px;
                padding: 0 12px;
                border: 1px solid #777;
                border-radius: 4px;
                outline: none;
                color: #f1f1f1;
                background: #121212;
                font: inherit;
            }
            .ytmp-room-dialog__field input::placeholder { color: #aaa; }
            .ytmp-room-dialog__field input:focus-visible,
            .ytmp-room-dialog__button:focus-visible {
                outline: 2px solid #3ea6ff;
                outline-offset: 2px;
            }
            .ytmp-room-dialog__field input:focus-visible { border-color: #3ea6ff; }
            .ytmp-room-dialog__actions {
                display: flex;
                justify-content: flex-end;
                gap: 8px;
                padding: 8px 16px 16px;
            }
            .ytmp-room-dialog__button {
                min-width: 64px;
                min-height: 40px;
                padding: 0 12px;
                border: 0;
                border-radius: 20px;
                color: #3ea6ff;
                background: transparent;
                font: 500 14px Roboto, Arial, sans-serif;
                cursor: pointer;
            }
            .ytmp-room-dialog__button:hover { background: rgba(62, 166, 255, .12); }
            @media (max-width: 480px) {
                dialog.ytmp-room-dialog { border-radius: 8px; }
                .ytmp-room-dialog__header { padding: 20px 20px 8px; }
                .ytmp-room-dialog__body { padding: 16px 20px 20px; }
            }
        `;
        document.head.append(style);
    }

    const dialog = document.createElement("dialog");
    dialog.className = "ytmp-room-dialog";
    dialog.setAttribute("aria-labelledby", "ytmp-room-dialog-title");
    const form = document.createElement("form");
    const header = document.createElement("header");
    header.className = "ytmp-room-dialog__header";
    const title = document.createElement("h2");
    title.id = "ytmp-room-dialog-title";
    title.className = "ytmp-room-dialog__title";
    title.textContent = options.title;
    header.append(title);
    form.append(header);

    const body = document.createElement("div");
    body.className = "ytmp-room-dialog__body";
    for (const row of options.rows ?? []) {
        const rowElement = document.createElement("div");
        rowElement.className = "ytmp-room-dialog__row";
        const label = document.createElement("span");
        label.className = "ytmp-room-dialog__label";
        label.textContent = row.label;
        const value = document.createElement("p");
        value.className = "ytmp-room-dialog__value";
        value.textContent = row.value;
        rowElement.append(label, value);
        body.append(rowElement);
    }

    const inputs = new Map<string, HTMLInputElement>();
    for (const field of options.fields ?? []) {
        const fieldElement = document.createElement("div");
        fieldElement.className = "ytmp-room-dialog__field";
        const input = document.createElement("input");
        input.id = `ytmp-room-${field.name}`;
        input.name = field.name;
        input.type = field.type ?? "text";
        input.value = field.value;
        input.required = true;
        input.addEventListener("input", () => {
            input.setCustomValidity(input.value.trim() ? "" : "Enter a value.");
        });
        const label = document.createElement("label");
        label.htmlFor = input.id;
        label.textContent = field.label;
        fieldElement.append(label, input);
        body.append(fieldElement);
        inputs.set(field.name, input);
    }
    form.append(body);

    const actions = document.createElement("footer");
    actions.className = "ytmp-room-dialog__actions";
    const closeButton = document.createElement("button");
    closeButton.className = "ytmp-room-dialog__button";
    closeButton.type = "button";
    closeButton.textContent = options.onSubmit ? "Cancel" : "Close";
    closeButton.autofocus = true;
    closeButton.addEventListener("click", () => dialog.close());
    actions.append(closeButton);

    if (options.onSubmit) {
        const submitButton = document.createElement("button");
        submitButton.className = "ytmp-room-dialog__button";
        submitButton.type = "submit";
        submitButton.textContent = options.submitLabel ?? "Save";
        actions.append(submitButton);
        form.addEventListener("submit", (event) => {
            event.preventDefault();
            for (const input of inputs.values()) {
                input.setCustomValidity(
                    input.value.trim() ? "" : "Enter a value."
                );
            }
            if (!form.reportValidity()) return;
            const values = Object.fromEntries(
                [...inputs].map(([name, input]) => [name, input.value.trim()])
            );
            dialog.close();
            options.onSubmit?.(values);
        });
    }
    form.append(actions);

    dialog.append(form);
    dialog.addEventListener("click", (event) => {
        if (event.target === dialog) dialog.close();
    });
    dialog.addEventListener("close", () => dialog.remove(), { once: true });
    document.body.append(dialog);
    dialog.showModal();
    (inputs.values().next().value as HTMLInputElement | undefined)?.focus();
}

function createButtonLeave(
    socket: Socket,
    config: ReturnType<typeof getConfig>
) {
    setTimeout(async () => {
        const btn = createButton({
            children: "Leave Room",
            onClick: async () => {
                console.log("Leaving room");
                const fp = await firstValueFrom(fp$);
                socket.emit("leave", {
                    id: config.roomId,
                    fingerprint: fp,
                });
                localStorage.removeItem("roomId");
                window.location.reload();
            },
            join: false,
        });
        document
            .querySelector(
                "[class='scroller scroller-on-hover style-scope ytmusic-guide-section-renderer']"
            )
            ?.append(btn);
    }, 2000);
}

function createButtonRoomInformation(socket: Socket) {
    setTimeout(() => {
        const btn = createButton({
            children: "Room Information",
            join: false,
            onClick: () => {
                const config = getConfig();
                showRoomDialog({
                    title: "Room Information",
                    rows: [
                        { label: "Room ID", value: config.roomId || "Not joined" },
                        {
                            label: "Party URL",
                            value: config.partyUrl || DEFAULT_PARTY_URL,
                        },
                        {
                            label: "Connection",
                            value: socket.connected ? "Connected" : "Disconnected",
                        },
                    ],
                });
            },
        });
        document
            .querySelector(
                "[class='scroller scroller-on-hover style-scope ytmusic-guide-section-renderer']"
            )
            ?.append(btn);
    }, 2000);
}

function createJoinButton() {
    setTimeout(async () => {
        const btn = createButton({
            children: "Join Room",
            onClick: () => {
                const currentConfig = getConfig();
                showRoomDialog({
                    title: "Join Room",
                    fields: [
                        {
                            name: "roomId",
                            label: "Room ID",
                            value: currentConfig.roomId || "",
                        },
                        {
                            name: "partyUrl",
                            label: "Party URL",
                            value: currentConfig.partyUrl || DEFAULT_PARTY_URL,
                            type: "url",
                        },
                    ],
                    submitLabel: "Join",
                    onSubmit: (values) => {
                        localStorage.setItem("roomId", values.roomId);
                        localStorage.setItem("partyUrl", values.partyUrl);
                        window.location.reload();
                    },
                });
            },
            join: true,
        });
        document
            .querySelector(
                "[class='scroller scroller-on-hover style-scope ytmusic-guide-section-renderer']"
            )
            ?.append(btn);
    }, 2000);
}

function getAppInstance<T>() {
    const app = document.querySelector("ytmusic-app");
    return app as Element & {
        networkManager: {
            fetch: (url: string, init?: object) => Promise<T>;
        };
    };
}

function getQueueInstance() {
    const q = document.querySelector("#queue");
    (globalThis as any).queue = q;

    setInterval(() => {
        (globalThis as any).queue = document.querySelector(
            "#queue"
        ) as Element & {
            dispatch: (action: any) => void;
            queue: {
                store: {
                    store: {
                        dispatch: (action: any) => void;
                        getState: () => any;
                    };
                };
            };
        };
    }, 300);

    return (globalThis as any).queue;
}

function collectVideoIds(value: any, ids = new Set<string>(), seen = new WeakSet<object>()) {
    if (!value || typeof value !== "object" || seen.has(value)) return ids;
    seen.add(value);

    if (Array.isArray(value)) {
        value.forEach((item) => collectVideoIds(item, ids, seen));
        return ids;
    }

    for (const [key, child] of Object.entries(value)) {
        if (key === "videoId" && typeof child === "string") {
            ids.add(child);
        } else if (child && typeof child === "object") {
            collectVideoIds(child, ids, seen);
        }
    }

    return ids;
}

function getQueueVideoIds(queue: any, queueState: any) {
    const ids = collectVideoIds(queueState);

    queue?.querySelectorAll('a[href*="watch?v="]').forEach((anchor: HTMLAnchorElement) => {
        try {
            const videoId = new URL(anchor.href, window.location.origin).searchParams.get("v");
            if (videoId) ids.add(videoId);
        } catch {
            // Ignore malformed queue links.
        }
    });

    return ids;
}

const queueItemsBeingAdded = new Set<string>();

async function addQueue(videoIds: string[]) {
    const uniqueVideoIds = [...new Set(videoIds.filter(Boolean))];
    if (!uniqueVideoIds.length) return;

    const app = getAppInstance();
    const queue = getQueueInstance();
    const store = queue?.queue.store.store;
    if (!app || !store) return;

    const queueState = store.getState().queue;
    const existingVideoIds = getQueueVideoIds(queue, queueState);
    const videoIdsToAdd = uniqueVideoIds.filter((videoId) => {
        if (existingVideoIds.has(videoId) || queueItemsBeingAdded.has(videoId)) {
            return false;
        }
        queueItemsBeingAdded.add(videoId);
        return true;
    });
    if (!videoIdsToAdd.length) return;

    const payload = {
        queueContextParams: queueState.queueContextParams,
        queueInsertPosition: "INSERT_AT_END",
        videoIds: videoIdsToAdd,
    };

    try {
        const result = await app.networkManager.fetch("music/get_queue", payload);
        if (
            result &&
            typeof result === "object" &&
            "queueDatas" in result &&
            Array.isArray(result.queueDatas)
        ) {
            const currentQueueState = store.getState().queue;
            const queueItems = currentQueueState.items ?? [];
            const currentVideoIds = getQueueVideoIds(queue, currentQueueState);
            const addedVideoIds = new Set<string>();
            const items = result.queueDatas
                .map((it) =>
                    typeof it === "object" && it && "content" in it
                        ? it.content
                        : null
                )
                .filter((item): item is NonNullable<typeof item> => Boolean(item))
                .filter((item: any) => {
                    const itemVideoIds = collectVideoIds(item);
                    const videoId = videoIdsToAdd.find((requestedId) => itemVideoIds.has(requestedId));
                    if (!videoId) return true;
                    if (currentVideoIds.has(videoId) || addedVideoIds.has(videoId)) {
                        return false;
                    }
                    addedVideoIds.add(videoId);
                    return true;
                });
            if (!items.length) return;
            queue?.dispatch({
                type: "ADD_ITEMS",
                payload: {
                    nextQueueItemId: currentQueueState.nextQueueItemId,
                    index: queueItems.length,
                    items,
                    shuffleEnabled: false,
                    shouldAssignIds: true,
                },
            });
            removeListParameter();
        }
    } finally {
        videoIdsToAdd.forEach((videoId) => queueItemsBeingAdded.delete(videoId));
    }
}
document.addEventListener("DOMContentLoaded", async () => {
    const config = getConfig();

    const socket = io(config.partyUrl || DEFAULT_PARTY_URL);
    const ROOM_ID = config.roomId as string;

    createButtonRoomInformation(socket);

    if (config.partyUrl && config.roomId) {
        createButtonLeave(socket, config);
    } else {
        createJoinButton();
    }

    let queues: Queue[] = [];
    let observedVideo: HTMLVideoElement | null = null;
    let lastPublishedPlaybackSnapshot = "";
    let playbackSyncTimer: number | undefined;

    const publishPlaybackState = (
        state: "playing" | "paused" | "standby",
        force = false
    ) => {
        const currentlyPlaying = getNowPlaying();
        const snapshot = JSON.stringify({ state, currentlyPlaying });
        if (!force && snapshot === lastPublishedPlaybackSnapshot) return;
        lastPublishedPlaybackSnapshot = snapshot;
        socket.emit("playbackState", { roomId: ROOM_ID, state, currentlyPlaying });
    };

    const readPlaybackState = (video: HTMLVideoElement) => {
        const state = getVideoPlaybackState(video);
        if (state === "playing") removeListParameter();
        publishPlaybackState(state);
    };

    const observePlaybackState = (force = false) => {
        const video = document.querySelector(
            "#movie_player > div.html5-video-container > video"
        ) as HTMLVideoElement | null;
        if (!video) {
            observedVideo = null;
            publishPlaybackState("standby", force);
            return;
        }

        if (video !== observedVideo) {
            observedVideo = video;
            ["play", "playing", "pause", "ended", "emptied", "loadstart"].forEach(
                (eventName) => video.addEventListener(eventName, () => readPlaybackState(video))
            );
        }
        const state = getVideoPlaybackState(video);
        if (state === "playing") removeListParameter();
        publishPlaybackState(state, force);
    };

    socket.on("joined", async (data: Queue[]) => {
        queues = data;
        observePlaybackState(true);
        if (!playbackSyncTimer) {
            playbackSyncTimer = window.setInterval(() => observePlaybackState(), 1000);
        }
        if (data[0] && getPlaybackState().state === "standby") {
            play(data[0]);
        }
        setTimeout(async () => {
            await addQueue(data.map((q) => q.url));
        }, 1000);
    });

    socket.on("leave", async () => {
        localStorage.removeItem("roomId");
        window.location.reload();
    });

    const join$ = from(
        axios.get("https://ifconfig.me/all.json", {
            headers: {
                "Content-Type": "application/json",
                Accept: "application/json",
            },
        })
    ).pipe(
        switchMap((res) => {
            return new Promise<{ id: string; browser: string; ip: string }>(
                (resolve, reject) => {
                    try {
                        const info = detect();

                        const browser = [
                            (info?.name?.slice(0, 1).toUpperCase() || "") +
                                (info?.name?.slice(1) || ""),
                            info?.os, // Mac OS, Windows
                        ]; // [Chrome, Mac OS]

                        const accountButton: HTMLButtonElement | null =
                            document.querySelector(
                                '[aria-label="Open avatar menu"]'
                            );

                        if (!accountButton) {
                            resolve({
                                id: config.roomId || "",
                                browser:
                                    browser.filter(Boolean).join(" ") || "",
                                ip: res.data.ip_addr || "",
                            });
                            return;
                        }

                        accountButton.click();

                        const querySelector = document.querySelector(
                            '[class="style-scope tp-yt-iron-dropdown"]'
                        ) as HTMLDivElement;
                        if (querySelector) {
                            querySelector.style.display = "hidden";
                        }
                        accountButton.click();
                        if (querySelector) {
                            querySelector.style.display = "inherit";
                        }

                        setTimeout(() => {
                            accountButton.click();
                            const user: HTMLDivElement | null =
                                document.querySelector("#account-name");

                            if (!user) {
                                resolve({
                                    id: config.roomId || "",
                                    browser:
                                        browser.filter(Boolean).join(" ") || "",
                                    ip: res.data.ip_addr || "",
                                });
                                return;
                            }

                            // add user to browser
                            browser.unshift(user?.textContent);

                            resolve({
                                id: config.roomId || "",
                                browser:
                                    browser.filter(Boolean).join(" ") || "",
                                ip: res.data.ip_addr || "",
                            });
                        }, 300);
                    } catch (error) {
                        console.log(error);
                        reject(error);
                    }
                }
            );
        }),
        switchMap(async (data) => {
            const fp = await firstValueFrom(fp$);

            return {
                ...data,
                fingerprint: fp,
            };
        }),
        tap(async (data) => {
            if (data.id) {
                socket.emit("join", data);
            }
        })
    );

    const playbackObserver = new MutationObserver((mutations) => {
        mutations.forEach((mutation, i) => {
            if (
                mutation.type === "childList" &&
                i == 0 &&
                mutation.target.textContent
            ) {
                setTimeout(() => {
                    const playback = getPlaybackState();
                    observePlaybackState();

                    const videoId = getVideoId();

                    socket.emit("started", {
                        roomId: ROOM_ID,
                        videoId: videoId,
                    });

                    socket.emit("notify", {
                        message: `Now playing: ___"${playback.song}"___ by ${playback.artist} 🎧`,
                        roomId: ROOM_ID,
                    });
                }, 1000);
            }
        });
    });

    const titleElement = document.querySelector(".title.ytmusic-player-bar");
    if (titleElement) {
        playbackObserver.observe(titleElement, {
            childList: true,
            subtree: true,
        });
    }

    socket.on("connect", async () => {
        console.log("Connected to WebSocket server with ID:", socket.id);
        join$.subscribe();
    });

    socket.on("play", () => {
        observePlaybackState();
        const playback = getPlaybackState();

        if (playback.state == "standby" && queues[0]) {
            play(queues[0]);
            return;
        }

        if (playback.state == "standby" && !queues[0]) {
            socket.emit("notify", {
                message: `🚫 No tracks in the queue right now.`,
                roomId: ROOM_ID,
            });
            return;
        }

        play();

        socket.emit("notify", {
            message: `Now playing: ___"${playback.song}"___ by ${playback.artist} 🎧`,
            roomId: ROOM_ID,
        });
    });

    socket.on("pause", () => {
        pause();

        const playback = getPlaybackState();

        socket.emit("notify", {
            message: `⏸️ ___${playback.song}___ - ${playback.artist} is now paused`,
            roomId: ROOM_ID,
        });
    });

    socket.on("next", () => {
        next();
    });

    socket.on("prev", () => {
        prev();
    });

    socket.on("volumeUp", () => {
        const currentVolume = volumeUp();

        // notify
        socket.emit("notify", {
            message: `🔊 Volume increased. Current volume: ${currentVolume}`,
            roomId: ROOM_ID,
        });
    });

    socket.on("volumeDown", () => {
        const currentVolume = volumeDown();

        // notify
        socket.emit("notify", {
            message: `🔊 Volume decreased. Current volume: ${currentVolume}`,
            roomId: ROOM_ID,
        });
    });

    socket.on("mute", () => {
        mute();
        socket.emit("notify", {
            message: "🤫 Shhh... we're on mute. Enjoy the silence (for now)!",
            roomId: ROOM_ID,
        });
    });

    socket.on("unmute", () => {
        mute();
        socket.emit("notify", {
            message: "🎶 We're back! Audio unmuted—let the music play!",
            roomId: ROOM_ID,
        });
    });

    socket.on("lyrics", async () => {
        const txt =
            (await lyrics()) ||
            "🤷‍♀️ No lyrics this time—guess we're freestyling!";

        socket.emit("notify", {
            message: txt,
            roomId: ROOM_ID,
        });
    });

    socket.on("resume", () => {
        resume();
    });

    socket.on("addToQueue", async ({ videoId }: { videoId: string }) => {
        const playback = getPlaybackState();
        console.log("addToQueue", videoId);

        if (playback.state == "standby") {
            queues.push({
                id: crypto.randomUUID(),
                url: videoId,
            });
            return;
        }

        await addQueue([videoId]);
    });

    socket.on("disconnect", () => {
        console.log("Disconnected from WebSocket server");
    });
});
