/* eslint-disable @typescript-eslint/no-explicit-any */
import { from, tap, switchMap, firstValueFrom } from "rxjs";
import { io, Socket } from "socket.io-client";
import { detect } from "detect-browser";
import axios from "axios";
import { load } from "@fingerprintjs/fingerprintjs";
import { DEFAULT_PARTY_URL } from "../constants/config";

const fp$ = from(load({})).pipe(
    switchMap(async (fp) => {
        return (await fp.get()).visitorId;
    })
);

Object.defineProperty(window, "onbeforeunload", {
    get: () => null,
    set: () => {},
    configurable: true,
});

function removeListParameter() {
    const url = new URL(window.location.href);
    if (!url.searchParams.has("list")) return;

    url.searchParams.delete("list");
    const cleanUrl = `${url.pathname}${url.search}${url.hash}`;
    const reloadKey = `music-party-list-cleanup:${url.pathname}:${url.searchParams.get("v") || "no-video"}`;

    try {
        if (window.sessionStorage.getItem(reloadKey)) {
            window.history.replaceState(window.history.state, "", cleanUrl);
            return;
        }
        window.sessionStorage.setItem(reloadKey, "1");
        window.location.replace(cleanUrl);
    } catch {
        window.history.replaceState(window.history.state, "", cleanUrl);
    }
}

function removeAutogeneratedRadioList() {
    const listId = new URL(window.location.href).searchParams.get("list");
    if (listId?.startsWith("RDAMVM")) removeListParameter();
}

removeAutogeneratedRadioList();
window.addEventListener("yt-navigate-finish", removeAutogeneratedRadioList);
window.addEventListener("popstate", removeAutogeneratedRadioList);

function getPlayerVideoData(): any {
    const player = document.querySelector("#movie_player") as
        | (HTMLElement & { getVideoData?: () => any })
        | null;
    try {
        return player?.getVideoData?.() ?? null;
    } catch {
        return null;
    }
}

function getVideoElement() {
    return document.querySelector(
        "#movie_player > div.html5-video-container > video"
    ) as HTMLVideoElement | null;
}

function getVideoPlaybackState(video: HTMLVideoElement | null) {
    if (!video || video.ended) return "standby" as const;
    if (!video.paused) return "playing" as const;
    if (video.currentSrc || video.src || video.readyState > 0 || getVideoId()) {
        return "paused" as const;
    }
    return "standby" as const;
}

function getVideoId(): string | null {
    const playerVideoId = getPlayerVideoData()?.video_id;
    if (typeof playerVideoId === "string" && playerVideoId) return playerVideoId;

    const u = document
        .querySelector('[class="ytp-title-link yt-uix-sessionlink"]')
        ?.getAttribute("href");
    if (!u) return null;
    return new URL(u, window.location.origin).searchParams.get("v");
}

function getPlaybackState(): {
    song: string;
    artist: string;
    state: "playing" | "paused" | "standby";
    el: HTMLVideoElement;
} {
    const el = getVideoElement() as HTMLVideoElement;

    const song =
        document.querySelector(".title.ytmusic-player-bar")?.textContent?.trim() ||
        "Unknown title";

    const state = getVideoPlaybackState(el);
    if (state !== "standby") {
        return {
            song,
            artist: getCurrentArtist(),
            state,
            el,
        };
    }
    return {
        el: el as HTMLVideoElement,
        song,
        state: "standby",
        artist: "",
    };
}

type Queue = { id: string; url: string };
type NowPlaying = {
    videoId: string | null;
    title: string;
    artist: string;
    artwork: string | null;
};

function getNowPlaying(): NowPlaying | null {
    const video = getVideoElement();
    if (video?.ended) return null;

    const playerVideoData = getPlayerVideoData();
    const videoId =
        getVideoId() ||
        (typeof playerVideoData?.video_id === "string" ? playerVideoData.video_id : null) ||
        new URL(window.location.href).searchParams.get("v");
    const title =
        document.querySelector(".title.ytmusic-player-bar")?.textContent?.trim() ||
        (typeof playerVideoData?.title === "string" ? playerVideoData.title.trim() : "");
    if (!title) return null;

    return {
        videoId,
        title: title || "Unknown title",
        artist: getCurrentArtist(),
        artwork: videoId ? `https://img.youtube.com/vi/${videoId}/hqdefault.jpg` : null,
    };
}

function navigateToQueueItem(queue: Queue) {
    const currentUrl = new URL(window.location.href);
    if (currentUrl.searchParams.get("v") === queue.url) return false;

    const targetUrl = new URL("/watch", window.location.origin);
    targetUrl.searchParams.set("v", queue.url);
    targetUrl.searchParams.set("qid", queue.id);
    window.location.assign(targetUrl.toString());
    return true;
}

function getCurrentArtist(): string {
    const byline = document.querySelector(
        "ytmusic-player-bar yt-formatted-string.byline"
    );
    const bylineText =
        byline?.getAttribute("title") || byline?.textContent || "";
    const artistName = bylineText.split("•")[0]?.trim();
    if (artistName) return artistName;

    return byline?.querySelector("a")?.textContent?.trim() || "Unknown artist";
}

function play(queue?: Queue) {
    const playback = getPlaybackState();
    if (queue?.url && playback.state === "standby") {
        navigateToQueueItem(queue);
        return;
    }
    if (playback.state === "paused") {
        void playback.el.play().then(
            () => window.setTimeout(removeListParameter, 250),
            removeListParameter
        );
        return;
    }
    removeListParameter();
}

/**
 * Pause the video
 */
function pause() {
    const VIDEO_SELECTOR = "#movie_player > div.html5-video-container > video";
    const vid = document.querySelector(VIDEO_SELECTOR) as HTMLVideoElement;
    if (vid) {
        vid.pause();
    }
    // const el = document.getElementById(
    //     "play-pause-button"
    // ) as HTMLButtonElement;
    // if (!el) return;
    // el.click();
}

function volumeUp(): number {
    const event = new KeyboardEvent("keydown", { key: "=" });
    document.dispatchEvent(event);

    // get current volume
    const video = document.querySelector(
        "#movie_player > div.html5-video-container > video"
    ) as HTMLVideoElement;

    if (video) {
        return video.volume * 100;
    }

    return 0;
}

function volumeDown(): number {
    const event = new KeyboardEvent("keydown", { key: "-" });
    document.dispatchEvent(event);

    // get current volume
    const video = document.querySelector(
        "#movie_player > div.html5-video-container > video"
    ) as HTMLVideoElement;

    if (video) {
        return video.volume * 100;
    }

    return 0;
}

function mute() {
    const VIDEO_SELECTOR = ".volume";

    const el = document.querySelector(VIDEO_SELECTOR) as HTMLButtonElement;

    if (el) {
        el.click();
    }
}

function lyrics() {
    const tab = document.querySelector(
        "#tabsContent > tp-yt-paper-tab:nth-child(3)"
    ) as HTMLButtonElement | null;
    if (!tab) return Promise.resolve(null);

    tab.click();

    return new Promise((resolve) => {
        setTimeout(() => {
            const text = document.querySelector(
                "#contents > ytmusic-description-shelf-renderer > div > yt-formatted-string.non-expandable.description.style-scope.ytmusic-description-shelf-renderer"
            )?.textContent?.trim();

            tab.click();
            resolve(text || null);
        }, 1000);
    });
}

function next(queue?: Queue) {
    if (queue?.url) {
        navigateToQueueItem(queue);
        return;
    }

    const NEXT_SELECTOR = ".next-button";

    const el = document.querySelector(NEXT_SELECTOR) as HTMLButtonElement;

    if (el) {
        el.click();
    }
}

function prev() {
    const PREV_SELECTOR = ".previous-button";

    const el = document.querySelector(PREV_SELECTOR) as HTMLButtonElement;

    if (el) {
        el.click();
    }
}

function resume() {
    const VIDEO_SELECTOR = "play-pause-button";

    const el = document.querySelector(VIDEO_SELECTOR) as HTMLButtonElement;

    if (el) {
        el.click();
    }
}

function getConfig() {
    const config = {
        partyUrl: localStorage.getItem("partyUrl"),
        roomId: localStorage.getItem("roomId"),
    };

    return config;
}

const roomPanelRefreshers = new Set<() => void>();

function createButton({
    onClick,
    children,
    icon,
}: {
    onClick: any;
    children: string;
    icon: "create" | "join" | "leave" | "info" | "settings" | "server" | "queue" | "members";
}) {
    // const wrapBtn = document.createElement("ytmusic-guide-entry-renderer");
    const btn = document.createElement("tp-yt-paper-item");
    btn.setAttribute("role", "link");
    btn.classList.add("style-scope", "ytmusic-guide-entry-renderer");
    btn.setAttribute("style-target", "host");
    btn.setAttribute("tabindex", "0");
    btn.setAttribute("aria-disabled", "false");
    btn.setAttribute("aria-current", "false");
    const svg = document.createElementNS("http://www.w3.org/2000/svg", "svg");
    svg.setAttribute("fill", "none");
    svg.setAttribute("viewBox", "0 0 24 24");
    svg.setAttribute("stroke-width", "1.5");
    svg.setAttribute("stroke", "currentColor");
    svg.style.width = "20px";
    svg.style.height = "20px";

    const iconPaths = {
        create: "M12 8v8m-4-4h8m5 0a9 9 0 1 1-18 0 9 9 0 0 1 18 0Z",
        join: "M12 4.5v15m7.5-7.5h-15",
        leave: "M15.75 9V5.25A2.25 2.25 0 0 0 13.5 3h-6a2.25 2.25 0 0 0-2.25 2.25v13.5A2.25 2.25 0 0 0 7.5 21h6a2.25 2.25 0 0 0 2.25-2.25V15M12 9l-3 3m0 0 3 3m-3-3h12.75",
        info: "M11.25 11.25h1.5v5.25m-.75-8.25h.008v.008H12V8.25Zm9 3.75a9 9 0 1 1-18 0 9 9 0 0 1 18 0Z",
        settings: "M4 6h16M4 12h16M4 18h16",
        server: "M4.5 6.75h15m-15 5.25h15m-15 5.25h15M7.5 6.75h.008v.008H7.5V6.75Zm0 5.25h.008v.008H7.5V12Zm0 5.25h.008v.008H7.5V17.25Z",
        queue: "M8 6h13M8 12h13M8 18h13M3 6h.01M3 12h.01M3 18h.01",
        members: "M16 21v-2a4 4 0 0 0-4-4H8a4 4 0 0 0-4 4v2m16 0v-2a4 4 0 0 0-3-3.87M14 3.13a4 4 0 0 1 0 7.75M14 7a4 4 0 1 1-8 0 4 4 0 0 1 8 0Z",
    } as const;
    const path = document.createElementNS("http://www.w3.org/2000/svg", "path");
    path.setAttribute("stroke-linecap", "round");
    path.setAttribute("stroke-linejoin", "round");
    path.setAttribute("d", iconPaths[icon]);

    svg.appendChild(path);
    if (icon === "settings") {
        for (const [cx, cy] of [[9, 6], [15, 12], [11, 18]]) {
            const knob = document.createElementNS("http://www.w3.org/2000/svg", "circle");
            knob.setAttribute("cx", String(cx));
            knob.setAttribute("cy", String(cy));
            knob.setAttribute("r", "1.5");
            knob.setAttribute("fill", "currentColor");
            svg.appendChild(knob);
        }
    }

    const txt = document.createElement("span");
    txt.style.margin = "0 20px";

    txt.textContent = children;
    btn.appendChild(svg);
    btn.appendChild(txt);

    btn.addEventListener("click", onClick);

    return btn;

    // wrapBtn.appendChild(btn);
    // return wrapBtn;
}

type RoomDialogOptions = {
    title: string;
    rows?: Array<{ label: string; value: string }>;
    content?: Node;
    fields?: Array<{
        name: string;
        label: string;
        value: string;
        type?: "text" | "url";
    }>;
    submitLabel?: string;
    onSubmit?: (values: Record<string, string>) => void;
};

function showRoomDialog(options: RoomDialogOptions): HTMLDialogElement {
    if (!document.getElementById("ytmp-room-dialog-style")) {
        const style = document.createElement("style");
        style.id = "ytmp-room-dialog-style";
        style.textContent = `
            dialog.ytmp-room-dialog {
                width: min(420px, calc(100vw - 32px));
                max-width: calc(100vw - 32px);
                max-height: calc(100vh - 32px);
                padding: 0;
                border: 0;
                border-radius: 12px;
                color: #f1f1f1;
                background: #282828;
                box-shadow: 0 12px 32px rgba(0, 0, 0, .45);
                font: 14px/1.45 Roboto, Arial, sans-serif;
            }
            dialog.ytmp-room-dialog::backdrop { background: rgba(0, 0, 0, .64); }
            .ytmp-room-dialog form { margin: 0; }
            .ytmp-room-dialog__header { padding: 24px 24px 8px; }
            .ytmp-room-dialog__title {
                margin: 0;
                color: #f1f1f1;
                font-size: 20px;
                font-weight: 500;
                line-height: 28px;
            }
            .ytmp-room-dialog__body {
                display: grid;
                gap: 18px;
                max-height: min(60vh, 480px);
                overflow-y: auto;
                padding: 16px 24px 24px;
            }
            .ytmp-room-settings { display: grid; gap: 10px; }
            .ytmp-room-settings__row {
                display: flex;
                align-items: center;
                justify-content: space-between;
                gap: 12px;
                min-height: 38px;
                color: #f1f1f1;
            }
            .ytmp-room-settings__row label { cursor: pointer; }
            .ytmp-room-settings__stepper { display: flex; align-items: center; gap: 10px; }
            .ytmp-room-settings__stepper button {
                width: 36px;
                height: 36px;
                border: 1px solid #777;
                border-radius: 50%;
                color: #f1f1f1;
                background: #383838;
                font: inherit;
                cursor: pointer;
            }
            .ytmp-room-settings__stepper button:disabled { opacity: .5; cursor: default; }
            .ytmp-room-settings__error { margin: 0; color: #ff8a8a; }
            .ytmp-room-settings__share {
                min-height: 40px;
                border: 0;
                border-radius: 20px;
                padding: 0 14px;
                color: #3ea6ff;
                background: rgba(62, 166, 255, .12);
                font: 500 14px Roboto, Arial, sans-serif;
                cursor: pointer;
            }
            .ytmp-room-settings__share:hover { background: rgba(62, 166, 255, .2); }
            .ytmp-room-settings__share:focus-visible { outline: 2px solid #3ea6ff; outline-offset: 2px; }
            .ytmp-room-settings input:focus-visible,
            .ytmp-room-settings button:focus-visible { outline: 2px solid #3ea6ff; outline-offset: 2px; }
            .ytmp-room-dialog__row, .ytmp-room-dialog__field {
                display: grid;
                gap: 6px;
                min-width: 0;
            }
            .ytmp-room-dialog__label { color: #c6c6c6; font-size: 12px; }
            .ytmp-room-dialog__value {
                margin: 0;
                color: #f1f1f1;
                overflow-wrap: anywhere;
            }
            .ytmp-room-live-panel { display: grid; gap: 12px; }
            .ytmp-room-live-panel__status { margin: 0; color: #c6c6c6; font-size: 13px; }
            .ytmp-room-live-panel__list { display: grid; gap: 0; margin: 0; padding: 0; list-style: none; }
            .ytmp-room-live-panel__item { display: grid; gap: 4px; min-width: 0; padding: 12px 0; border-top: 1px solid #454545; }
            .ytmp-room-live-panel__title { overflow: hidden; color: #f1f1f1; font-weight: 500; text-overflow: ellipsis; }
            .ytmp-room-live-panel__detail { color: #aaa; font-size: 12px; }
            .ytmp-room-live-panel__empty { margin: 0; padding: 16px 0; border-top: 1px solid #454545; color: #aaa; }
            .ytmp-room-dialog__field label { color: #f1f1f1; }
            .ytmp-room-dialog__field input {
                box-sizing: border-box;
                width: 100%;
                min-height: 44px;
                padding: 0 12px;
                border: 1px solid #777;
                border-radius: 4px;
                outline: none;
                color: #f1f1f1;
                background: #121212;
                font: inherit;
            }
            .ytmp-room-dialog__field input::placeholder { color: #aaa; }
            .ytmp-room-dialog__field input:focus-visible,
            .ytmp-room-dialog__button:focus-visible {
                outline: 2px solid #3ea6ff;
                outline-offset: 2px;
            }
            .ytmp-room-dialog__field input:focus-visible { border-color: #3ea6ff; }
            .ytmp-room-dialog__actions {
                display: flex;
                justify-content: flex-end;
                gap: 8px;
                padding: 8px 16px 16px;
            }
            .ytmp-room-dialog__button {
                min-width: 64px;
                min-height: 40px;
                padding: 0 12px;
                border: 0;
                border-radius: 20px;
                color: #3ea6ff;
                background: transparent;
                font: 500 14px Roboto, Arial, sans-serif;
                cursor: pointer;
            }
            .ytmp-room-dialog__button:hover { background: rgba(62, 166, 255, .12); }
            @media (max-width: 480px) {
                dialog.ytmp-room-dialog { border-radius: 8px; }
                .ytmp-room-dialog__header { padding: 20px 20px 8px; }
                .ytmp-room-dialog__body { padding: 16px 20px 20px; }
            }
        `;
        document.head.append(style);
    }

    const dialog = document.createElement("dialog");
    dialog.className = "ytmp-room-dialog";
    dialog.setAttribute("aria-labelledby", "ytmp-room-dialog-title");
    const form = document.createElement("form");
    const header = document.createElement("header");
    header.className = "ytmp-room-dialog__header";
    const title = document.createElement("h2");
    title.id = "ytmp-room-dialog-title";
    title.className = "ytmp-room-dialog__title";
    title.textContent = options.title;
    header.append(title);
    form.append(header);

    const body = document.createElement("div");
    body.className = "ytmp-room-dialog__body";
    for (const row of options.rows ?? []) {
        const rowElement = document.createElement("div");
        rowElement.className = "ytmp-room-dialog__row";
        const label = document.createElement("span");
        label.className = "ytmp-room-dialog__label";
        label.textContent = row.label;
        const value = document.createElement("p");
        value.className = "ytmp-room-dialog__value";
        value.textContent = row.value;
        rowElement.append(label, value);
        body.append(rowElement);
    }

    const inputs = new Map<string, HTMLInputElement>();
    for (const field of options.fields ?? []) {
        const fieldElement = document.createElement("div");
        fieldElement.className = "ytmp-room-dialog__field";
        const input = document.createElement("input");
        input.id = `ytmp-room-${field.name}`;
        input.name = field.name;
        input.type = field.type ?? "text";
        input.value = field.value;
        input.required = true;
        input.addEventListener("input", () => {
            input.setCustomValidity(input.value.trim() ? "" : "Enter a value.");
        });
        const label = document.createElement("label");
        label.htmlFor = input.id;
        label.textContent = field.label;
        fieldElement.append(label, input);
        body.append(fieldElement);
        inputs.set(field.name, input);
    }
    if (options.content) body.append(options.content);
    form.append(body);

    const actions = document.createElement("footer");
    actions.className = "ytmp-room-dialog__actions";
    const closeButton = document.createElement("button");
    closeButton.className = "ytmp-room-dialog__button";
    closeButton.type = "button";
    closeButton.textContent = options.onSubmit ? "Cancel" : "Close";
    closeButton.autofocus = true;
    closeButton.addEventListener("click", () => dialog.close());
    actions.append(closeButton);

    if (options.onSubmit) {
        const submitButton = document.createElement("button");
        submitButton.className = "ytmp-room-dialog__button";
        submitButton.type = "submit";
        submitButton.textContent = options.submitLabel ?? "Save";
        actions.append(submitButton);
        form.addEventListener("submit", (event) => {
            event.preventDefault();
            for (const input of inputs.values()) {
                input.setCustomValidity(
                    input.value.trim() ? "" : "Enter a value."
                );
            }
            if (!form.reportValidity()) return;
            const values = Object.fromEntries(
                [...inputs].map(([name, input]) => [name, input.value.trim()])
            );
            dialog.close();
            options.onSubmit?.(values);
        });
    }
    form.append(actions);

    dialog.append(form);
    dialog.addEventListener("click", (event) => {
        if (event.target === dialog) dialog.close();
    });
    dialog.addEventListener("close", () => dialog.remove(), { once: true });
    document.body.append(dialog);
    dialog.showModal();
    (inputs.values().next().value as HTMLInputElement | undefined)?.focus();
    return dialog;
}

type RoomSettings = {
    id: string;
    name: string;
    chatId: string;
    createdAt: string;
    feature: {
        minimumVotes: number;
        maxQueueSize: number;
        nextCommand: boolean;
        nextOnlyAdmin: boolean;
        previousCommand: boolean;
        previousOnlyAdmin: boolean;
        volumeCommand: boolean;
        muteCommand: boolean;
        unmuteCommand: boolean;
        silentNotifications: boolean;
    };
};

async function requestRoomSettings(config: ReturnType<typeof getConfig>, update?: Record<string, number | boolean>) {
    if (!config.roomId) throw new Error("Join a room before changing its settings.");
    const baseUrl = (config.partyUrl || DEFAULT_PARTY_URL).replace(/\/$/, "");
    const response = await fetch(`${baseUrl}/api/rooms/${encodeURIComponent(config.roomId)}${update ? "/settings" : ""}`, {
        method: update ? "PATCH" : "GET",
        headers: update ? { "Content-Type": "application/json" } : undefined,
        body: update ? JSON.stringify(update) : undefined,
    });
    if (!response.ok) {
        const result = await response.json().catch(() => ({}));
        throw new Error(typeof result.message === "string" ? result.message : "Could not reach the room server.");
    }
    return response.json() as Promise<RoomSettings | { ok: boolean }>;
}

function createRoomSettingsContent(config: ReturnType<typeof getConfig>, room: RoomSettings) {
    const content = document.createElement("div");
    content.className = "ytmp-room-settings";
    const error = document.createElement("p");
    error.className = "ytmp-room-settings__error";
    error.setAttribute("role", "alert");
    const busy = new Set<string>();

    const save = async (key: string, value: number | boolean, control: HTMLInputElement | HTMLButtonElement) => {
        if (busy.has(key)) return;
        busy.add(key);
        content.querySelectorAll<HTMLInputElement | HTMLButtonElement>(`[data-setting="${key}"]`).forEach((field) => { field.disabled = true; });
        error.textContent = "";
        try {
            await requestRoomSettings(config, { [key]: value });
            if (key === "minimumVotes" || key === "maxQueueSize") {
                room.feature[key] = value as number;
                const valueLabel = content.querySelector(`[data-value="${key}"]`);
                if (valueLabel) valueLabel.textContent = String(value);
                const minusButton = content.querySelector<HTMLButtonElement>(`[data-step="${key}:-1"]`);
                if (minusButton) minusButton.disabled = typeof value === "number" && value <= 1;
            }
        } catch (caught) {
            error.textContent = caught instanceof Error ? caught.message : "Could not update room settings.";
            if (control instanceof HTMLInputElement) control.checked = !value;
        } finally {
            busy.delete(key);
            content.querySelectorAll<HTMLInputElement | HTMLButtonElement>(`[data-setting="${key}"]`).forEach((field) => { field.disabled = false; });
            if (key === "minimumVotes" || key === "maxQueueSize") {
                const minusButton = content.querySelector<HTMLButtonElement>(`[data-step="${key}:-1"]`);
                if (minusButton) minusButton.disabled = room.feature[key] <= 1;
            }
        }
    };

    const addStepper = (label: string, key: "minimumVotes" | "maxQueueSize", step: number) => {
        const row = document.createElement("div");
        row.className = "ytmp-room-settings__row";
        const title = document.createElement("span");
        title.textContent = label;
        const stepper = document.createElement("div");
        stepper.className = "ytmp-room-settings__stepper";
        for (const delta of [-step, step]) {
            const button = document.createElement("button");
            button.type = "button";
            button.textContent = delta < 0 ? "−" : "+";
            button.setAttribute("aria-label", `${delta < 0 ? "Decrease" : "Increase"} ${label.toLowerCase()}`);
            button.dataset.setting = key;
            button.dataset.step = `${key}:${delta < 0 ? "-1" : "1"}`;
            button.disabled = delta < 0 && room.feature[key] <= 1;
            button.addEventListener("click", () => void save(key, Math.max(1, room.feature[key] + delta), button));
            stepper.append(button);
        }
        const value = document.createElement("b");
        value.dataset.value = key;
        value.setAttribute("aria-live", "polite");
        value.textContent = String(room.feature[key]);
        stepper.insertBefore(value, stepper.lastChild);
        row.append(title, stepper);
        content.append(row);
    };

    const addToggle = (label: string, key: keyof RoomSettings["feature"]) => {
        const row = document.createElement("div");
        row.className = "ytmp-room-settings__row";
        const text = document.createElement("label");
        const input = document.createElement("input");
        input.type = "checkbox";
        input.checked = Boolean(room.feature[key]);
        input.dataset.setting = key;
        input.addEventListener("change", () => void save(key, input.checked, input));
        text.append(input, document.createTextNode(` ${label}`));
        row.append(text);
        content.append(row);
    };

    content.append(createRoomInviteButton(room.id, config.partyUrl || DEFAULT_PARTY_URL, error));
    addStepper("Minimum skip votes", "minimumVotes", 1);
    addStepper("Maximum queue size", "maxQueueSize", 5);
    addToggle("/next and skip voting", "nextCommand");
    addToggle("Next command admin-only", "nextOnlyAdmin");
    addToggle("/prev", "previousCommand");
    addToggle("Previous command admin-only", "previousOnlyAdmin");
    addToggle("Volume controls", "volumeCommand");
    addToggle("/mute", "muteCommand");
    addToggle("/unmute", "unmuteCommand");
    addToggle("Silent Telegram notifications", "silentNotifications");
    if (navigator.userAgent.includes("Electron/")) {
        const telegramButton = document.createElement("button");
        telegramButton.className = "ytmp-room-settings__share";
        telegramButton.type = "button";
        telegramButton.textContent = "Telegram Settings";
        telegramButton.addEventListener("click", () => {
            content.closest("dialog")?.close();
            window.setTimeout(() => window.dispatchEvent(new Event("music-party:open-telegram-settings")), 0);
        });
        content.append(telegramButton);
    }
    content.append(error);
    return content;
}

function createRoomInviteButton(roomId: string, partyUrl: string, feedback: HTMLElement) {
    const button = document.createElement("button");
    button.className = "ytmp-room-settings__share";
    button.type = "button";
    button.textContent = "Copy invite link";
    button.addEventListener("click", async () => {
        let succeeded = false;
        feedback.textContent = "";
        button.disabled = true;
        try {
            let inviteBaseUrl = partyUrl;
            const currentUrl = new URL(partyUrl);
            if (["127.0.0.1", "localhost", "[::1]"].includes(currentUrl.hostname)) {
                if (!navigator.userAgent.includes("Electron/")) {
                    throw new Error("This room is local to this computer. Open it in Music Party Desktop to create a public invite link.");
                }
                button.textContent = "Creating temporary link…";
                inviteBaseUrl = await requestDesktopInviteServerUrl(roomId);
            }
            const url = new URL(inviteBaseUrl);
            url.pathname = "/";
            url.search = "";
            url.searchParams.set("room", roomId);
            await navigator.clipboard.writeText(url.toString());
            button.textContent = "Invite link copied";
            window.setTimeout(() => { button.textContent = "Copy invite link"; }, 1800);
            succeeded = true;
        } catch (caught) {
            feedback.textContent = caught instanceof Error ? caught.message : "Could not copy the invite link.";
            button.textContent = "Copy invite link";
        } finally {
            button.disabled = false;
            if (!succeeded && button.textContent === "Creating temporary link…") button.textContent = "Copy invite link";
        }
    });
    return button;
}

function requestDesktopInviteServerUrl(roomId: string) {
    return new Promise<string>((resolve, reject) => {
        const resultKey = "music-party:invite-link-result";
        const readyEvent = "music-party:invite-link-ready";
        const timeout = window.setTimeout(() => {
            window.removeEventListener(readyEvent, onReady);
            reject(new Error("Cloudflare Quick Tunnel did not respond. Try again."));
        }, 65_000);
        const onReady = () => {
            window.clearTimeout(timeout);
            const rawResult = localStorage.getItem(resultKey);
            localStorage.removeItem(resultKey);
            try {
                const result = JSON.parse(rawResult || "{}") as { serverUrl?: string; error?: string };
                if (!result.serverUrl) throw new Error(result.error || "Could not create a temporary invite link.");
                resolve(result.serverUrl);
            } catch (error) {
                reject(error instanceof Error ? error : new Error("Could not create a temporary invite link."));
            }
        };
        localStorage.removeItem(resultKey);
        window.addEventListener(readyEvent, onReady, { once: true });
        window.dispatchEvent(new Event("music-party:create-invite-link"));
        if (!roomId.trim()) {
            window.clearTimeout(timeout);
            window.removeEventListener(readyEvent, onReady);
            reject(new Error("Join a room before creating an invite link."));
        }
    });
}

function createButtonRoomSettings() {
    if (!navigator.userAgent.includes("Electron/")) return;
    setTimeout(() => {
        const btn = createButton({
            children: "Room Settings",
            icon: "settings",
            onClick: async () => {
                const config = getConfig();
                try {
                    const room = await requestRoomSettings(config) as RoomSettings;
                    showRoomDialog({
                        title: "Room Settings",
                        rows: [
                            { label: "Room ID", value: room.id },
                            { label: "Created", value: new Date(room.createdAt).toLocaleString() },
                            { label: "Telegram", value: room.chatId || "Not linked" },
                        ],
                        content: createRoomSettingsContent(config, room),
                    });
                } catch (error) {
                    showRoomDialog({
                        title: "Room Settings",
                        rows: [{ label: "Settings unavailable", value: error instanceof Error ? error.message : "Could not load room settings." }],
                    });
                }
            },
        });
        document
            .querySelector("[class='scroller scroller-on-hover style-scope ytmusic-guide-section-renderer']")
            ?.append(btn);
    }, 2000);
}

function createButtonLeave(
    socket: Socket,
    config: ReturnType<typeof getConfig>
) {
    setTimeout(async () => {
        const btn = createButton({
            children: "Leave Room",
            icon: "leave",
            onClick: async () => {
                console.log("Leaving room");
                const fp = await firstValueFrom(fp$);
                socket.emit("leave", {
                    id: config.roomId,
                    fingerprint: fp,
                });
                localStorage.removeItem("roomId");
                window.location.reload();
            },
        });
        document
            .querySelector(
                "[class='scroller scroller-on-hover style-scope ytmusic-guide-section-renderer']"
            )
            ?.append(btn);
    }, 2000);
}

function createButtonRoomInformation(socket: Socket) {
    setTimeout(() => {
        const btn = createButton({
            children: "Room Information",
            icon: "info",
            onClick: () => {
                const config = getConfig();
                const feedback = document.createElement("p");
                feedback.className = "ytmp-room-settings__error";
                feedback.setAttribute("role", "status");
                const content = document.createElement("div");
                content.className = "ytmp-room-settings";
                content.append(createRoomInviteButton(config.roomId || "", config.partyUrl || DEFAULT_PARTY_URL, feedback), feedback);
                showRoomDialog({
                    title: "Room Information",
                    content,
                    rows: [
                        { label: "Room ID", value: config.roomId || "" },
                        {
                            label: "Party URL",
                            value: config.partyUrl || DEFAULT_PARTY_URL,
                        },
                        {
                            label: "Connection",
                            value: socket.connected ? "Connected" : "Disconnected",
                        },
                    ],
                });
            },
        });
        document
            .querySelector(
                "[class='scroller scroller-on-hover style-scope ytmusic-guide-section-renderer']"
            )
            ?.append(btn);
    }, 2000);
}

function createRoomDataButton(kind: "queue" | "members") {
    setTimeout(() => {
        const isQueue = kind === "queue";
        const button = createButton({
            children: isQueue ? "Queue" : "Room Members",
            icon: isQueue ? "queue" : "members",
            onClick: () => {
                const config = getConfig();
                const content = document.createElement("section");
                content.className = "ytmp-room-live-panel";
                const status = document.createElement("p");
                status.className = "ytmp-room-live-panel__status";
                const list = document.createElement("ul");
                list.className = "ytmp-room-live-panel__list";
                content.append(status, list);

                const refresh = async () => {
                    if (!config.partyUrl || !config.roomId) {
                        status.textContent = "Join a room to see its shared queue and members.";
                        list.replaceChildren();
                        return;
                    }
                    status.textContent = isQueue ? "Loading the shared queue…" : "Loading room members…";
                    try {
                        const baseUrl = config.partyUrl.replace(/\/$/, "");
                        const response = await fetch(`${baseUrl}/api/rooms/${encodeURIComponent(config.roomId)}`);
                        const room = await response.json().catch(() => ({})) as {
                            message?: string;
                            queue?: Array<{ url?: string; title?: string; addedBy?: string | null }>;
                            devices?: Array<{ name?: string; createdAt?: string }>;
                        };
                        if (!response.ok) throw new Error(room.message || "Could not load room information.");
                        const entries = isQueue ? room.queue ?? [] : room.devices ?? [];
                        status.textContent = isQueue
                            ? `${entries.length} ${entries.length === 1 ? "track" : "tracks"} in the shared queue`
                            : `${entries.length} ${entries.length === 1 ? "player has" : "players have"} joined this room`;
                        list.replaceChildren();
                        if (entries.length === 0) {
                            const empty = document.createElement("li");
                            empty.className = "ytmp-room-live-panel__empty";
                            empty.textContent = isQueue
                                ? "No tracks are waiting. Add a song in YouTube Music to put it in the room queue."
                                : "No players have joined yet. Share the room details so others can connect.";
                            list.append(empty);
                            return;
                        }
                        for (const entry of entries) {
                            const item = document.createElement("li");
                            item.className = "ytmp-room-live-panel__item";
                            const title = document.createElement("span");
                            title.className = "ytmp-room-live-panel__title";
                            const detail = document.createElement("span");
                            detail.className = "ytmp-room-live-panel__detail";
                            if (isQueue) {
                                const track = entry as { url?: string; title?: string; addedBy?: string | null };
                                title.textContent = track.title?.trim() || track.url || "Untitled track";
                                detail.textContent = track.addedBy ? `Added by ${track.addedBy}` : "Added to the room queue";
                            } else {
                                const member = entry as { name?: string; createdAt?: string };
                                title.textContent = member.name?.trim() || "Player";
                                detail.textContent = member.createdAt
                                    ? `Joined ${new Date(member.createdAt).toLocaleString()}`
                                    : "Joined this room";
                            }
                            item.append(title, detail);
                            list.append(item);
                        }
                    } catch (error) {
                        status.textContent = error instanceof Error ? error.message : "Could not load room information.";
                        list.replaceChildren();
                    }
                };
                const dialog = showRoomDialog({ title: isQueue ? "Room Queue" : "Room Members", content });
                roomPanelRefreshers.add(refresh);
                dialog.addEventListener("close", () => roomPanelRefreshers.delete(refresh), { once: true });
                void refresh();
            },
        });
        document
            .querySelector("[class='scroller scroller-on-hover style-scope ytmusic-guide-section-renderer']")
            ?.append(button);
    }, 2000);
}

function createServerSettingsButton() {
    if (!navigator.userAgent.includes("Electron/")) return;
    setTimeout(() => {
        const button = createButton({
            children: "Server Settings",
            icon: "server",
            onClick: () => window.dispatchEvent(new Event("music-party:open-server-settings")),
        });
        document
            .querySelector("[class='scroller scroller-on-hover style-scope ytmusic-guide-section-renderer']")
            ?.append(button);
    }, 2000);
}

function createJoinButton() {
    setTimeout(async () => {
        const btn = createButton({
            children: "Join Room",
            icon: "join",
            onClick: () => {
                const currentConfig = getConfig();
                showRoomDialog({
                    title: "Join Room",
                    fields: [
                        {
                            name: "roomId",
                            label: "Room ID",
                            value: currentConfig.roomId || "",
                        },
                        {
                            name: "partyUrl",
                            label: "Party URL",
                            value: currentConfig.partyUrl || DEFAULT_PARTY_URL,
                            type: "url",
                        },
                    ],
                    submitLabel: "Join",
                    onSubmit: (values) => {
                        localStorage.setItem("roomId", values.roomId);
                        localStorage.setItem("partyUrl", values.partyUrl);
                        window.location.reload();
                    },
                });
            },
        });
        document
            .querySelector(
                "[class='scroller scroller-on-hover style-scope ytmusic-guide-section-renderer']"
            )
            ?.append(btn);
    }, 2000);
}

function createRoomButton() {
    setTimeout(() => {
        const btn = createButton({
            children: "Create Room",
            icon: "create",
            onClick: () => {
                const savedHandle = localStorage.getItem("music-party-handle")?.trim();
                showRoomDialog({
                    title: "Create Room",
                    fields: [
                        { name: "name", label: "Room name", value: "My listening room" },
                        { name: "handle", label: "Your name", value: savedHandle || `Guest-${crypto.randomUUID().slice(0, 8)}` },
                    ],
                    submitLabel: "Create",
                    onSubmit: async (values) => {
                        const partyUrl = getConfig().partyUrl || DEFAULT_PARTY_URL;
                        const baseUrl = partyUrl.replace(/\/$/, "");
                        const apiRequest = async <T,>(path: string, body?: Record<string, string>): Promise<T> => {
                            const response = await fetch(`${baseUrl}${path}`, {
                                method: "POST",
                                headers: { "Content-Type": "application/json" },
                                body: body ? JSON.stringify(body) : undefined,
                            });
                            if (!response.ok) {
                                const result = await response.json().catch(() => ({}));
                                throw new Error(typeof result.message === "string" ? result.message : "Could not create room.");
                            }
                            return response.json() as Promise<T>;
                        };
                        try {
                            const generated = await apiRequest<{ id: string }>("/api/rooms/generate");
                            const room = await apiRequest<{ id: string }>("/api/rooms", { id: generated.id, name: values.name });
                            await apiRequest(`/api/rooms/${encodeURIComponent(room.id)}/join`, { handle: values.handle });
                            localStorage.setItem("roomId", room.id);
                            localStorage.setItem("partyUrl", partyUrl);
                            localStorage.setItem("music-party-handle", values.handle);
                            window.location.reload();
                        } catch (caught) {
                            showRoomDialog({
                                title: "Could not create room",
                                rows: [{ label: "Error", value: caught instanceof Error ? caught.message : "Could not create room." }],
                            });
                        }
                    },
                });
            },
        });
        document
            .querySelector("[class='scroller scroller-on-hover style-scope ytmusic-guide-section-renderer']")
            ?.append(btn);
    }, 2000);
}

function getAppInstance<T>() {
    const app = document.querySelector("ytmusic-app");
    return app as Element & {
        networkManager: {
            fetch: (url: string, init?: object) => Promise<T>;
        };
    };
}

function getQueueInstance() {
    return document.querySelector("#queue") as (Element & {
        dispatch: (action: any) => void;
        queue: {
            store: {
                store: {
                    dispatch: (action: any) => void;
                    getState: () => any;
                };
            };
        };
    }) | null;
}

async function waitForQueueRuntime(timeoutMs = 15000) {
    const deadline = Date.now() + timeoutMs;
    while (Date.now() < deadline) {
        const app = getAppInstance() as any;
        const queue = getQueueInstance();
        const store = queue?.queue?.store?.store as any;
        const queueState = store?.getState?.().queue;
        if (
            typeof app?.networkManager?.fetch === "function" &&
            typeof store?.getState === "function" &&
            queueState?.queueContextParams
        ) {
            return { app, queue, store, queueState };
        }
        await new Promise((resolve) => window.setTimeout(resolve, 250));
    }
    throw new Error("YouTube Music queue did not become ready within 15 seconds.");
}

function collectVideoIds(value: any, ids = new Set<string>(), seen = new WeakSet<object>()) {
    if (!value || typeof value !== "object" || seen.has(value)) return ids;
    seen.add(value);

    if (Array.isArray(value)) {
        value.forEach((item) => collectVideoIds(item, ids, seen));
        return ids;
    }

    for (const [key, child] of Object.entries(value)) {
        if (key === "videoId" && typeof child === "string") {
            ids.add(child);
        } else if (child && typeof child === "object") {
            collectVideoIds(child, ids, seen);
        }
    }

    return ids;
}

function getQueueVideoIds(queue: any, queueState: any) {
    const ids = collectVideoIds(queueState?.items ?? []);
    const currentVideoId = getVideoId();
    if (currentVideoId) ids.add(currentVideoId);

    queue?.querySelectorAll('a[href*="watch?v="]').forEach((anchor: HTMLAnchorElement) => {
        try {
            const videoId = new URL(anchor.href, window.location.origin).searchParams.get("v");
            if (videoId) ids.add(videoId);
        } catch {
            // Ignore malformed queue links.
        }
    });

    return ids;
}

const queueItemsBeingAdded = new Set<string>();

async function addQueue(videoIds: string[]) {
    const uniqueVideoIds = [...new Set(videoIds.filter(Boolean))];
    if (!uniqueVideoIds.length) return;

    let runtime: Awaited<ReturnType<typeof waitForQueueRuntime>>;
    try {
        runtime = await waitForQueueRuntime();
    } catch (error) {
        console.warn("Could not add room tracks to YouTube Music queue:", error);
        return;
    }
    const { app, queue, store, queueState } = runtime;
    const existingVideoIds = getQueueVideoIds(queue, queueState);
    const videoIdsToAdd = uniqueVideoIds.filter((videoId) => {
        if (existingVideoIds.has(videoId) || queueItemsBeingAdded.has(videoId)) {
            return false;
        }
        queueItemsBeingAdded.add(videoId);
        return true;
    });
    if (!videoIdsToAdd.length) return;

    const payload = {
        queueContextParams: queueState.queueContextParams,
        queueInsertPosition: "INSERT_AT_END",
        videoIds: videoIdsToAdd,
    };

    try {
        const result = await app.networkManager.fetch("music/get_queue", payload);
        if (
            result &&
            typeof result === "object" &&
            "queueDatas" in result &&
            Array.isArray(result.queueDatas)
        ) {
            const currentQueueState = store.getState().queue;
            const queueItems = currentQueueState.items ?? [];
            const currentVideoIds = getQueueVideoIds(queue, currentQueueState);
            const addedVideoIds = new Set<string>();
            const items = result.queueDatas
                .map((it: any) =>
                    typeof it === "object" && it && "content" in it
                        ? it.content
                        : null
                )
                .filter((item: any) => Boolean(item))
                .filter((item: any) => {
                    const itemVideoIds = collectVideoIds(item);
                    const videoId = videoIdsToAdd.find((requestedId) => itemVideoIds.has(requestedId));
                    if (!videoId) return true;
                    if (currentVideoIds.has(videoId) || addedVideoIds.has(videoId)) {
                        return false;
                    }
                    addedVideoIds.add(videoId);
                    return true;
                });
            if (!items.length) return;
            queue?.dispatch({
                type: "ADD_ITEMS",
                payload: {
                    nextQueueItemId: currentQueueState.nextQueueItemId,
                    index: queueItems.length,
                    items,
                    shuffleEnabled: false,
                    shouldAssignIds: true,
                },
            });
            removeListParameter();
        }
    } catch (error) {
        console.warn("YouTube Music rejected room queue items:", error);
    } finally {
        videoIdsToAdd.forEach((videoId) => queueItemsBeingAdded.delete(videoId));
    }
}
document.addEventListener("DOMContentLoaded", async () => {
    const config = getConfig();

    const socket = io(config.partyUrl || DEFAULT_PARTY_URL);
    const ROOM_ID = config.roomId as string;

    createServerSettingsButton();
    const isJoined = Boolean(config.roomId?.trim());
    if (isJoined) {
        createButtonRoomInformation(socket);
        createRoomDataButton("queue");
        createRoomDataButton("members");
        createButtonLeave(socket, config);
        createButtonRoomSettings();
    } else {
        createRoomButton();
        createJoinButton();
    }

    socket.on("roomUpdated", () => {
        for (const refresh of roomPanelRefreshers) void refresh();
    });

    let queues: Queue[] = [];
    let observedVideo: HTMLVideoElement | null = null;
    let lastPublishedPlaybackSnapshot = "";
    let playbackSyncTimer: number | undefined;

    const publishPlaybackState = (
        state: "playing" | "paused" | "standby",
        force = false
    ) => {
        const currentlyPlaying = getNowPlaying();
        const snapshot = JSON.stringify({ state, currentlyPlaying });
        if (!force && snapshot === lastPublishedPlaybackSnapshot) return;
        lastPublishedPlaybackSnapshot = snapshot;
        socket.emit("playbackState", { roomId: ROOM_ID, state, currentlyPlaying });
    };

    const readPlaybackState = (video: HTMLVideoElement) => {
        const state = getVideoPlaybackState(video);
        if (state === "playing") removeListParameter();
        publishPlaybackState(state);
    };

    const observePlaybackState = (force = false) => {
        const video = document.querySelector(
            "#movie_player > div.html5-video-container > video"
        ) as HTMLVideoElement | null;
        if (!video) {
            observedVideo = null;
            publishPlaybackState("standby", force);
            return;
        }

        if (video !== observedVideo) {
            observedVideo = video;
            ["play", "playing", "pause", "ended", "emptied", "loadstart"].forEach(
                (eventName) => video.addEventListener(eventName, () => readPlaybackState(video))
            );
        }
        const state = getVideoPlaybackState(video);
        if (state === "playing") removeListParameter();
        publishPlaybackState(state, force);
    };

    socket.on("joined", async (data: Queue[]) => {
        queues = data;
        observePlaybackState(true);
        if (!playbackSyncTimer) {
            playbackSyncTimer = window.setInterval(() => observePlaybackState(), 1000);
        }
        if (data[0] && getPlaybackState().state === "standby") {
            play(data[0]);
        }
        setTimeout(async () => {
            await addQueue(data.map((q) => q.url));
        }, 1000);
    });

    socket.on("leave", async () => {
        localStorage.removeItem("roomId");
        window.location.reload();
    });

    const join$ = from(
        axios.get("https://ifconfig.me/all.json", {
            headers: {
                "Content-Type": "application/json",
                Accept: "application/json",
            },
        })
    ).pipe(
        switchMap((res) => {
            return new Promise<{ id: string; browser: string; ip: string }>(
                (resolve, reject) => {
                    try {
                        const info = detect();

                        const browser = [
                            (info?.name?.slice(0, 1).toUpperCase() || "") +
                                (info?.name?.slice(1) || ""),
                            info?.os, // Mac OS, Windows
                        ]; // [Chrome, Mac OS]

                        const accountButton: HTMLButtonElement | null =
                            document.querySelector(
                                '[aria-label="Open avatar menu"]'
                            );

                        if (!accountButton) {
                            resolve({
                                id: config.roomId || "",
                                browser:
                                    browser.filter(Boolean).join(" ") || "",
                                ip: res.data.ip_addr || "",
                            });
                            return;
                        }

                        accountButton.click();

                        const querySelector = document.querySelector(
                            '[class="style-scope tp-yt-iron-dropdown"]'
                        ) as HTMLDivElement;
                        if (querySelector) {
                            querySelector.style.display = "hidden";
                        }
                        accountButton.click();
                        if (querySelector) {
                            querySelector.style.display = "inherit";
                        }

                        setTimeout(() => {
                            accountButton.click();
                            const user: HTMLDivElement | null =
                                document.querySelector("#account-name");

                            if (!user) {
                                resolve({
                                    id: config.roomId || "",
                                    browser:
                                        browser.filter(Boolean).join(" ") || "",
                                    ip: res.data.ip_addr || "",
                                });
                                return;
                            }

                            // add user to browser
                            browser.unshift(user?.textContent);

                            resolve({
                                id: config.roomId || "",
                                browser:
                                    browser.filter(Boolean).join(" ") || "",
                                ip: res.data.ip_addr || "",
                            });
                        }, 300);
                    } catch (error) {
                        console.log(error);
                        reject(error);
                    }
                }
            );
        }),
        switchMap(async (data) => {
            const fp = await firstValueFrom(fp$);

            return {
                ...data,
                fingerprint: fp,
            };
        }),
        tap(async (data) => {
            if (data.id) {
                socket.emit("join", data);
            }
        })
    );

    const playbackObserver = new MutationObserver((mutations) => {
        mutations.forEach((mutation, i) => {
            if (
                mutation.type === "childList" &&
                i == 0 &&
                mutation.target.textContent
            ) {
                setTimeout(() => {
                    const playback = getPlaybackState();
                    observePlaybackState();

                    const videoId = getVideoId();

                    socket.emit("started", {
                        roomId: ROOM_ID,
                        videoId: videoId,
                    });

                    socket.emit("notify", {
                        message: `Now playing: ___"${playback.song}"___ by ${playback.artist} 🎧`,
                        roomId: ROOM_ID,
                    });
                }, 1000);
            }
        });
    });

    const titleElement = document.querySelector(".title.ytmusic-player-bar");
    if (titleElement) {
        playbackObserver.observe(titleElement, {
            childList: true,
            subtree: true,
        });
    }

    socket.on("connect", async () => {
        console.log("Connected to WebSocket server with ID:", socket.id);
        join$.subscribe();
    });

    socket.on("play", () => {
        observePlaybackState();
        const playback = getPlaybackState();

        if (playback.state == "standby" && queues[0]) {
            play(queues[0]);
            return;
        }

        if (playback.state == "standby" && !queues[0]) {
            socket.emit("notify", {
                message: `🚫 No tracks in the queue right now.`,
                roomId: ROOM_ID,
            });
            return;
        }

        play();

        socket.emit("notify", {
            message: `Now playing: ___"${playback.song}"___ by ${playback.artist} 🎧`,
            roomId: ROOM_ID,
        });
    });

    socket.on("pause", () => {
        pause();

        const playback = getPlaybackState();

        socket.emit("notify", {
            message: `⏸️ ___${playback.song}___ - ${playback.artist} is now paused`,
            roomId: ROOM_ID,
        });
    });

    socket.on("next", () => {
        next();
    });

    socket.on("prev", () => {
        prev();
    });

    socket.on("volumeUp", () => {
        const currentVolume = volumeUp();

        // notify
        socket.emit("notify", {
            message: `🔊 Volume increased. Current volume: ${currentVolume}`,
            roomId: ROOM_ID,
        });
    });

    socket.on("volumeDown", () => {
        const currentVolume = volumeDown();

        // notify
        socket.emit("notify", {
            message: `🔊 Volume decreased. Current volume: ${currentVolume}`,
            roomId: ROOM_ID,
        });
    });

    socket.on("mute", () => {
        mute();
        socket.emit("notify", {
            message: "🤫 Shhh... we're on mute. Enjoy the silence (for now)!",
            roomId: ROOM_ID,
        });
    });

    socket.on("unmute", () => {
        mute();
        socket.emit("notify", {
            message: "🎶 We're back! Audio unmuted—let the music play!",
            roomId: ROOM_ID,
        });
    });

    socket.on("lyrics", async () => {
        const txt =
            (await lyrics()) ||
            "🤷‍♀️ No lyrics this time—guess we're freestyling!";

        socket.emit("notify", {
            message: txt,
            roomId: ROOM_ID,
        });
    });

    socket.on("resume", () => {
        resume();
    });

    socket.on("addToQueue", async ({ videoId }: { videoId: string }) => {
        const playback = getPlaybackState();
        console.log("addToQueue", videoId);

        if (playback.state == "standby") {
            queues.push({
                id: crypto.randomUUID(),
                url: videoId,
            });
            return;
        }

        await addQueue([videoId]);
    });

    socket.on("disconnect", () => {
        console.log("Disconnected from WebSocket server");
    });
});
